name: find_space
description: Find a space app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  get_it: ^7.2.0
  rxdart: ^0.28.0
  provider: ^6.0.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  json_annotation: ^4.9.0
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_native_splash: ^2.4.0
dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.19.1
  json_serializable: ^6.8.0
  freezed: ^2.4.1
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
